New uptream relase and add grub backgroud

diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -299,6 +299,14 @@ running_in_container()
   type running-in-container >/dev/null 2>&1 && running-in-container >/dev/null
 }
 
+run_grub_install()
+{
+    if ! grub-install $@ ; then
+        echo "Failed: grub-install $@" >&2
+        echo "WARNING: Bootloader is not properly installed, system may not be bootable" >&2
+    fi
+}
+
 case "$1" in
   configure)
     . /usr/share/debconf/confmodule
@@ -325,7 +333,7 @@ case "$1" in
         mkdir -p /boot/grub
 
         if test -e /boot/grub/device.map && ! test -e /boot/grub/core.img && \
-           ! test -e /boot/grub/@CPU_PLATFORM@/core.img; then
+           ! test -e /boot/grub/@FIRST_CPU_PLATFORM@/core.img; then
           # Looks like your device.map was generated by GRUB Legacy, which
           # used to generate broken device.map (see #422851).  Avoid the risk
           # by regenerating it.
@@ -411,6 +419,7 @@ case "$1" in
             # No || true here; it's vital that the user sees this, and it's
             # better to throw an error than to do the wrong thing.
             db_subst grub-pc/mixed_legacy_and_grub2 DISKS "$grub2_disks"
+            db_fset grub-pc/mixed_legacy_and_grub2 seen false
             db_input critical grub-pc/mixed_legacy_and_grub2
             db_go
             db_get grub-pc/mixed_legacy_and_grub2
@@ -444,7 +453,7 @@ case "$1" in
             # Using grub-probe instead of "(hd0)" avoids (UUID=) hack slowness
             # in case /boot/grub is not on (hd0) in device.map.
             echo "Generating core.img" >&2
-            grub-install --no-floppy --grub-setup=/bin/true "$(grub-probe -t drive /boot/grub)" > /dev/null
+            grub-install --target=i386-pc --no-floppy --grub-setup=/bin/true "$(grub-probe -t drive /boot/grub)" > /dev/null
 
             # Update menu.lst to reflect that:
             # - core.img is present now
@@ -460,9 +469,10 @@ case "$1" in
           # Skip grub-install in containers.
           :
         elif test -z "$2" || test -e /boot/grub/core.img || \
-             test -e /boot/grub/@CPU_PLATFORM@/core.img || \
+             test -e /boot/grub/@FIRST_CPU_PLATFORM@/core.img || \
              test "$UPGRADE_FROM_GRUB_LEGACY" || test "$wubi_device"; then
           question=grub-pc/install_devices
+          priority=high
           device_map="$(grub-mkdevicemap -m - | grep -v '^(fd[0-9]\+)' || true)"
           devices="$(echo "$device_map" | cut -f2)"
           if dpkg --compare-versions "$2" lt 1.98+20100702-1 && \
@@ -532,6 +542,7 @@ case "$1" in
             done
             if [ "$valid" = 0 ]; then
               question=grub-pc/install_devices_disks_changed
+              priority=critical
               db_set "$question" "$RET"
               db_fset "$question" seen false
               db_fset grub-pc/install_devices_empty seen false
@@ -578,13 +589,13 @@ case "$1" in
             done
             db_subst "$question" RAW_CHOICES "$ids"
             db_subst "$question" CHOICES "$descriptions"
-            db_input high "$question" || true
+            db_input "$priority" "$question" || true
             db_go
             db_get "$question"
             failed_devices=
             for i in `echo $RET | sed -e 's/, / /g'` ; do
               real_device="$(readlink -f "$i")"
-              if grub-install --force --no-floppy $real_device ; then
+              if grub-install --target=i386-pc --force --no-floppy $real_device ; then
                 # We just installed GRUB 2; then also generate grub.cfg.
                 touch /boot/grub/grub.cfg
               else
@@ -660,13 +671,12 @@ case "$1" in
         fi
 
         # /boot/grub/ has more chances of being accessible by GRUB
-        if test -e /boot/grub/grub.cfg ; then
-          for i in /usr/share/grub/unicode.pf2 ; do
-            if test -e $i ; then
-              cp $i /boot/grub/
-            fi
-          done
-        fi
+        for i in /usr/share/grub/unicode.pf2 ; do
+          if test -e $i ; then
+            mkdir -p /boot/grub
+            cp $i /boot/grub/
+          fi
+        done
 
         if [ "$fix_mixed_system" ]; then
           # These never contain any valuable information, and they aren't
@@ -679,14 +689,25 @@ case "$1" in
         fi
       ;;
 
-      grub-efi-ia32|grub-efi-amd64)
+      grub-efi-ia32|grub-efi-amd64|grub-efi-ia64|grub-efi-arm|grub-efi-arm64)
         bootloader_id="$(config_item GRUB_DISTRIBUTOR | tr A-Z a-z | \
                          cut -d' ' -f1)"
         case $bootloader_id in
           kubuntu) bootloader_id=ubuntu ;;
         esac
         if [ "$bootloader_id" ] && [ -d "/boot/efi/EFI/$bootloader_id" ]; then
-          grub-install
+          case @PACKAGE@ in
+            grub-efi-ia32)  target=i386-efi ;;
+            grub-efi-amd64) target=x86_64-efi ;;
+            grub-efi-ia64)  target=ia64-efi ;;
+            grub-efi-arm)   target=arm-efi ;;
+            grub-efi-arm64) target=arm64-efi ;;
+          esac
+          db_get grub2/force_efi_extra_removable
+          if [ "$RET" = true ]; then
+            FORCE_EXTRA_REMOVABLE="--force-extra-removable"
+          fi
+          run_grub_install --target="$target" "$FORCE_EXTRA_REMOVABLE"
         fi
 
         # /boot/grub/ has more chances of being accessible by GRUB
@@ -698,8 +719,30 @@ case "$1" in
         done
       ;;
 
+      grub-ieee1275)
+        case $(dpkg --print-architecture) in
+          ppc64el)
+            # Output may be empty; if so, just update the core image but
+            # don't install it to any PReP partition.
+            prep_bootdev="$(/usr/lib/grub/powerpc-ieee1275/prep-bootdev)"
+            run_grub_install --target=powerpc-ieee1275 $prep_bootdev
+          ;;
+        esac
+      ;;
+
       grub-yeeloong)
-        grub-install --target=mipsel-loongson
+        run_grub_install --target=mipsel-loongson
+      ;;
+
+      grub-xen)
+        # Install for x86_64 regardless of arch, since a 32-bit userspace can still boot with a 64-bit kernel.
+        mkdir -p /boot/xen
+        run_grub_install --target=x86_64-xen
+        case $(dpkg --print-architecture) in
+          i386)
+            run_grub_install --target=i386-xen
+          ;;
+        esac
       ;;
     esac
 
